name: CI – Order Backend Group B

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  conform:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  checkstyle:
    name: Checkstyle Lint
    runs-on: ubuntu-latest
    needs: [conform]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --stacktrace

  pmd:
    name: PMD Static Analysis
    runs-on: ubuntu-latest
    needs: [conform]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew pmdMain pmdTest --no-daemon --stacktrace

  spotbugs:
    name: SpotBugs Analysis
    runs-on: ubuntu-latest
    needs: [conform]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew spotbugsMain spotbugsTest --no-daemon --stacktrace

  tests:
    name: Unit Tests and Coverage
    runs-on: ubuntu-latest
    needs: [conform]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test --no-daemon --stacktrace

  build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [checkstyle, pmd, spotbugs, tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build --no-daemon --stacktrace

  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    needs: [conform]
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile